language: python
python:
  - "2.7"
  - "2.6"
env:
  - PGVERSION=9.1
  - PGVERSION=8.4
matrix:
  exclude:
    - python: "2.7"
      env: PGVERSION=8.4
    - python: "2.6"
      env: PGVERSION=9.1
install: ./bin/travis-build.sh
script: "nosetests --ckan --with-pylons=test.ini ckanext/b2/tests"
after_success:
  - coveralls
