language: python
python:
  - "2.7"
  - "2.6"
env:
  - PGVERSION=9.1
  - PGVERSION=8.4
matrix:
  exclude:
    - python: "2.7"
      env: PGVERSION=8.4
    - python: "2.6"
      env: PGVERSION=9.1
install: "pip install -r dev-requirements.txt"
script: "nosetests"
after_success:
  - coveralls
